### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by davidmigloz** [dzitkowskik/mini-dos#2]
> Functional specification of the project:
>   -Requirements 
>   -Architecture
>   -Major technical assumptions

**Comment by dzitkowskik** [comment]
start

**Comment by dzitkowskik** [comment]
sorry for that label crap

**Comment by ozanoz34** [comment]
This is the documentation's first draft, check it and give me feedbacks if you need, so i can make it better.

[dist. op. son.pdf](https://github.com/dzitkowskik/mini-dos/files/29433/dist.op.son.pdf)

**Comment by dzitkowskik** [comment]
I think now that we will have problem with casual consistency and we should write there FIFO (client centric can stay as it is)

**Comment by dzitkowskik** [comment]
1. That is not enough (documentation) it lucks explanation why our consistency will work, after all
2. if you do have it in word then send it like that not as PDF because I cannot add my comments
3. say there that project has two phases and if we will not have time for phase two we will add backup master instead
4. masted does not send any commands, he answers questions about where data is stored ans so on
5. like, where is data from tables A and B, he answers (A is on ip1: 12.123.123 and ip2: 13.123.123.3, B is on ip1: 191.21.123.33)
6. or is asked where to put new records (10 000 of them) to table A? and master answers: to nodes with ip 312.31.312.3, 12.123.132.31 and so on
7. RF can be set by us and don't have to be 3 it can be more or less if we want
8. you must write how example queries can look like, and that they must be handled by SQLite
9. we will use in memory database for all tables in master and for temporary tables in nodes

**Comment by dzitkowskik** [comment]
1. version is stored where the data is stored so not in master, it will be stored as additional column in node
2. example query: SELECT ID, SUM(money) FROM A LEFT JOIN B ON A.externalId = B.Id WHERE A.time > '12-12-2015' AND B.sth > 3;
3. About consistency why it will be working like that (so we get all records we have in all nodes that have this data, and we choose that one with highest version and so on)
4. We use very precise timestamp as some 64bit or 128bit integer and it will be a logic clock in phase II

**Comment by dzitkowskik** [comment]
I sent you to email more comments what to change
