### ISSUE TITLE
Master - Node failure (replication case)

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#29]
When master detects that node failed, it should replicate all the data he had to another node that does not have this data (unless there is less nodes left that replication factor). It will check in his in memory db what data it had. Then he will choose a node to do that task for him. He sends necessary information (which rows from which tables from which nodes should be copied to wich nodes) to that node, and node should perform necessary selects and inserts to replicate missing data.

**Comment by dzitkowskik** [comment]
Hmmm this explanation is really badly written:/ I should be more precise...
1. Master should detect that node failed
2. Then it should mark it and start process of replication of his data
3. It should get all necessary information from "big table" about data that node had
4. It should create replication task with data from (3) attached and assign that task to some node
5. It should also fix that data in "big table"
6. When process is done it should remove the node from list

**Comment by dzitkowskik** [comment]
If you think that this task is too big then I can split it to 2 or 3 smaller tasks

**Comment by davidmigloz** [comment]
Task finish. It works as follow:

1. Master in pinging nodes every `spanPingingTime` milliseconds.
2. When master cannot ping a node `REMOTE_EXCEPTION` or the node doesn't answer in time (`timeout` milliseconds) `TIMEOUT_EXPIRED`:
  1. Master marks that node has down. That means that node won't be used in any operation. But if it was needed in some operation, the node is mark as `needResetData`, because its data could not be consistent anymore. Master keeps pinging.
  2. If nodes recovers:
    + If `needResetData == true` -> master sends it a request to reset all its data. Node drops all the tables it has and creates all the tables sent by master (because during the down time new tables could have been created).
    + If `needResetData == false` -> continues as normal.
  3. If the number of retry attempts is greater than `maxRetryAttempts`, the node is unregistered from master:
    + Master seeks all data node had (which rowIDs from each table).
    + Unregisters node from `NodeManager`.
    + Deletes all records of node from in-memory db of master.
    + Chooses a new node where to replicate the data node had to maintain the `replicationFactor`. This node collects the data and stores it.
    + Replication task finished :)

**Comment by davidmigloz** [comment]
Task finish. It works as follow:

1. Master in pinging nodes every `spanPingingTime` milliseconds.
2. When master cannot ping a node `REMOTE_EXCEPTION` or the node doesn't answer in time (`timeout` milliseconds) `TIMEOUT_EXPIRED`:
  1. Master marks that node has down. That means that node won't be used in any operation. But if it was needed in some operation, the node is mark as `needResetData`, because its data could not be consistent anymore. Master keeps pinging.
  2. If nodes recovers:
    + If `needResetData == true` -> master sends it a request to reset all its data. Node drops all the tables it has and creates all the tables sent by master (because during the down time new tables could have been created). *Can be improved to not need to delete all data*.
    + If `needResetData == false` -> continues as normal.
  3. If the number of retry attempts is greater than `maxRetryAttempts`, the node is unregistered from master:
    + Master seeks all data node had (which rowIDs from each table).
    + Unregisters node from `NodeManager`.
    + Deletes all records of node from in-memory db of master.
    + Chooses a new node where to replicate the data node had to maintain the `replicationFactor`. This node collects the data and stores it.
    + Replication task finished :)

**Comment by davidmigloz** [comment]
UPDATE:
1. Master in pinging nodes every `spanPingingTime` milliseconds.
2. When master cannot ping a node `REMOTE_EXCEPTION` or the node doesn't answer in time (`timeout` milliseconds) `TIMEOUT_EXPIRED`:
   1. Master marks that node has down. That means that node won't be used in any operation. But if it was needed in some operation, the node is mark as `needToUpdate`, because new tables could have been created during down time. Master keeps pinging.
   2. If nodes recovers:
      - If `needToUpdate == true` -> master sends it a request to update its tables. Master sends node all create tables statements and node create the tables it doesn't have. Data of node can be outdated but as the selects are run in more than one node, the latest version will always be returned.
      - If `needToUpdate == false` -> continues as normal.
   3. If the number of retry attempts is greater than `maxRetryAttempts`, the node is unregistered from master:
      - Master seeks all data node had (which rowIDs from each table).
      - Unregisters node from `NodeManager`.
      - Deletes all records of node from in-memory db of master.
      - Chooses a new node where to replicate the data node had to maintain the `replicationFactor`. This node collects the data and stores it.
      - Replication task finished :)
