### ISSUE TITLE
Node  - Node failure (replication case)

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#32]
## See Node failure (replication case) - Master #29

Node should be able to handle replication task. Task contains information about data stored in errored node so all this data should be retrieved from its copies and transfered to other node pointed out by master. So:
1. Node gathers all data to replicate
2. Node inserts that data to another node
3. Node responses to master that he has done his job

(Need communication with David, to discuss details about what information will be sent from/to master, and the details of the process... confirmation, fault tolerance)

**Comment by davidmigloz** [comment]
Task finish. It works as follow:
1. Master in pinging nodes every `spanPingingTime` milliseconds.
2. When master cannot ping a node `REMOTE_EXCEPTION` or the node doesn't answer in time (`timeout` milliseconds) `TIMEOUT_EXPIRED`:
   1. Master marks that node has down. That means that node won't be used in any operation. But if it was needed in some operation, the node is mark as `needResetData`, because its data could not be consistent anymore. Master keeps pinging.
   2. If nodes recovers:
      - If `needResetData == true` -> master sends it a request to reset all its data. Node drops all the tables it has and creates all the tables sent by master (because during the down time new tables could have been created). _Can be improved to not need to delete all data_.
      - If `needResetData == false` -> continues as normal.
   3. If the number of retry attempts is greater than `maxRetryAttempts`, the node is unregistered from master:
      - Master seeks all data node had (which rowIDs from each table).
      - Unregisters node from `NodeManager`.
      - Deletes all records of node from in-memory db of master.
      - Chooses a new node where to replicate the data node had to maintain the `replicationFactor`. This node collects the data and stores it.
      - Replication task finished :)

**Comment by davidmigloz** [comment]
UPDATE:
1. Master in pinging nodes every `spanPingingTime` milliseconds.
2. When master cannot ping a node `REMOTE_EXCEPTION` or the node doesn't answer in time (`timeout` milliseconds) `TIMEOUT_EXPIRED`:
   1. Master marks that node has down. That means that node won't be used in any operation. But if it was needed in some operation, the node is mark as `needToUpdate`, because new tables could have been created during down time. Master keeps pinging.
   2. If nodes recovers:
      - If `needToUpdate == true` -> master sends it a request to update its tables. Master sends node all create tables statements and node create the tables it doesn't have. Data of node can be outdated but as the selects are run in more than one node, the latest version will always be returned.
      - If `needToUpdate == false` -> continues as normal.
   3. If the number of retry attempts is greater than `maxRetryAttempts`, the node is unregistered from master:
      - Master seeks all data node had (which rowIDs from each table).
      - Unregisters node from `NodeManager`.
      - Deletes all records of node from in-memory db of master.
      - Chooses a new node where to replicate the data node had to maintain the `replicationFactor`. This node collects the data and stores it.
      - Replication task finished :)
