### ISSUE TITLE
Task failure - retry

### ISSUE THREAD

**Issue by dzitkowskik** [dzitkowskik/mini-dos#60]
When task was failed it should be re-run (if possible) by different node, possibly on different subset of nodes. Think how to accomplish that and add comment here how it can be solved or was solved when ready:)

**Comment by davidmigloz** [comment]
Task done.
1. Master get an `ExecuteSQLRequest`.
2. It creates a new task assigned to a coordinator node.
3. If the task is completed without errors, results are sent to client.
4. If the task fails due to an user error (like an illegal sql query), the error is sent to client.
5.  If the task fails due to system errors (like a node crash), master tries to run the sql query again:
   
   a) A new task is created assigned to a new coordinator node. 
6. If the task fails again and the number of retry attempts is greater than `maxTaskRetryAttempts`, master gives up and sends the error to client.
